# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_scan_image', models.ImageField(upload_to=b'')),
                ('final_scan_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_scan_image', models.ImageField(upload_to=b'')),
                ('total_image', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=None, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(default=None, verbose_name='End Time')),
                ('total_time', models.FloatField(default=None, verbose_name='Start Time')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_scan_image', models.ImageField(upload_to=b'')),
                ('total_image', models.IntegerField()),
                ('video_url', models.URLField()),
            ],
        ),
    ]
